### ISSUE TITLE
SCP-049 revive heals them to full HP.

### ISSUE THREAD

**Issue by EMPFingers** [rby-blackruby/DocRework#1]
Reviving sets 049 back to their full health.

The 100 hp gained from the kill is from common-utils.

https://streamable.com/f1yxyj

```
doc_rework:
# Enable or disable DocRework's mechanics
  is_enabled: false
  # Allow SCP-049 to be healed for a percentage of it's missing health every player revival
  allow_doc_self_heal: true
  # Set the minimum cure amount for the buff area to kick in
  min_cures: 1
  # Change between 049's arua's heal type: 0 is for flat HP, 1 is for missing % HP
  heal_type: 0
  # Size of 049's healing radius
  heal_radius: 2.5999999
  # The amount of HP the Doc heals their Zombies
  heal_amount_flat: 15
  # The base amount of missing % HP the Doc heals their Zombies at the start of their buff
  zom_heal_amount_percentage: 10
  # Multiplier for the ZomHealAmountPercentage value every time a Doctor revives someone
  heal_percentage_multiplier: 1.29999995
  # Percentage of SCP-049's missing health to be healed
  doc_missing_health_percentage: 15
  # Cooldown for SCP049 active ability
  cooldown: 3000
  # Allow SCP-049-2 to damage everyone around upon hitting an enemy target
  allow_zombie_aoe: true
  # Amount of health each person in 049-2's range loses by 049-2's AOE attack
  zombie_aoe_damage: 30
  # Message sent to SCP-049 upon reaching the minimum cures amount required
  translation_passive_activation_message: >-
    <color=red>Your passive ability is now activated.

    You now heal zombies around you every 5 seconds.</color>
  # Message sent when you try to execute the .cr command when you're not a doctor
  translation_active_permission_denied: You are not allowed to use this command!
  # Message sent when you try to execute the .cr command but you don't yet have the min required revives
  translation_active_not_enough_revives: You don't have enough revives to use this ability!
  # Message sent when you try to execuwte the .cr command while it's on cooldown
  translation_active_on_cooldown: "Can't use this yet! Cooldown remaining: "
  # Message send when there are no spectators to spawn
  translation_active_no_spectators: Sorry, but we were unable to find any spectators for you. :(
  # Hint displayed when the .cr ability's cooldown has expired
  translation_active_ready_notification: >-
    <color=green>You can now use your active ability.

    Use .cr in your console to spawn a zombie from the spectators.</color>
```
